//
//  AnyAlertModels.swift
//  AnyAlert
//
//  Created by Chris Allinson on 2018-01-20.
//  Copyright (c) 2018 Chris Allinson. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - AnyAlert

public class AnyAlert: NSObject {
    
    var message: String
    
    var backgroundColor: UIColor
    var statusBarStyle: UIStatusBarStyle
    
    var messageFont: UIFont
    var messageColor: UIColor
    var closeButtonFont: UIFont
    var closeButtonColor: UIColor
    
    var height: Double
    
    var openSpeed: Double
    var closeSpeed: Double
    
    var doesSelfDismiss: Bool
    var showFor: Double
    
    @objc
    public init(message: String, backgroundColor: UIColor, statusBarStyle: UIStatusBarStyle, messageFont: UIFont, messageColor: UIColor, closeButtonFont: UIFont, closeButtonColor: UIColor, height: Double, openSpeed: Double, closeSpeed: Double, doesSelfDismiss: Bool, showFor: Double) {
        self.message = message
        
        self.backgroundColor = backgroundColor
        self.statusBarStyle = statusBarStyle
        
        self.messageFont = messageFont
        self.messageColor = messageColor
        self.closeButtonFont = closeButtonFont
        self.closeButtonColor = closeButtonColor
        
        self.height = height
        
        self.openSpeed = openSpeed
        self.closeSpeed = closeSpeed
        
        self.doesSelfDismiss = doesSelfDismiss
        self.showFor = showFor
    }
}


// MARK: - AnyAlertAction
enum AnyAlertAction {
    
    // MARK: Display
    
    enum Display {
        
        struct Request {
            var delegate: AnyAlertDelegate
            
            var id: String
            var message: String
            var backgroundColor: UIColor
            var statusBarStyle: UIStatusBarStyle
            var messageFont: UIFont
            var messageColor: UIColor
            var closeButtonFont: UIFont
            var closeButtonColor: UIColor
            var openSpeed: Double
            var closeSpeed: Double
            var doesSelfDismiss: Bool
            var showFor: Double
            
            var hasNavBar: Bool
            var parentVcName: String
            var initialStatusBarStyle: UIStatusBarStyle
            var startPositionY: Double
            var endPositionY: Double
        }
        
        struct Response {
            var delegate: AnyAlertDelegate
            
            var id: String
            var message: String
            var backgroundColor: UIColor
            var statusBarStyle: UIStatusBarStyle
            var messageFont: UIFont
            var messageColor: UIColor
            var closeButtonFont: UIFont
            var closeButtonColor: UIColor
            var openSpeed: Double
            var closeSpeed: Double
            var doesSelfDismiss: Bool
            var showFor: Double
            
            var hasNavBar: Bool
            var parentVcName: String
            var initialStatusBarStyle: UIStatusBarStyle
            var startPositionY: Double
            var endPositionY: Double
        }
        
        struct ViewModel {
            var message: String
            var backgroundColor: UIColor
            var statusBarStyle: UIStatusBarStyle
            var messageFont: UIFont
            var messageColor: UIColor
            var closeButtonFont: UIFont
            var closeButtonColor: UIColor
            var openSpeed: Double
            var closeSpeed: Double
            
            var shouldHideCloseButton: Bool
            var endPositionY: Double
        }
    }
    
    // MARK: Dismiss
    
    enum Dismiss {
        
        struct Request {
            var delegate: AnyAlertDelegate
            
            var id: String
            var closeSpeed: Double
            
            var hasNavBar: Bool
            var parentVcName: String
            var initialStatusBarStyle: UIStatusBarStyle
            var startPositionY: Double
            
            var immediately: Bool?
        }
        
        struct Response {
            var delegate: AnyAlertDelegate
            
            var id: String
            var closeSpeed: Double
            
            var hasNavBar: Bool
            var parentVcName: String
            var initialStatusBarStyle: UIStatusBarStyle
            var startPositionY: Double
            
            var immediately: Bool?
        }
        
        struct ViewModel {
            var closeSpeed: Double
            
            var startPositionY: Double
            
            var immediately: Bool?
        }
    }
}
