//
//  AnyAlertPresenter.swift
//  AnyAlert
//
//  Created by Chris Allinson on 2018-01-20.
//  Copyright (c) 2018 Chris Allinson. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol AnyAlertPresentationLogic {
    func displayAlert(response: AnyAlertAction.Display.Response)
    func dismissAlert(response: AnyAlertAction.Dismiss.Response)
}

class AnyAlertPresenter {
    
    // MARK: instance properties
    
    weak var viewController: AnyAlertDisplayLogic?
    
    
    
    // MARK: private methods
    
    private func performDismissAlert(delegate: AnyAlertDelegate, id: String, parentVcName: String, hasNavBar: Bool, initialStatusBarStyle: UIStatusBarStyle, startPositionY: Double, closeSpeed: Double, immediately: Bool? = false) {
        hideAlert(startPositionY: startPositionY, closeSpeed: closeSpeed, immediately: immediately!)
        updateStatusBar(id: id, immediately: immediately!, hasNavBar: hasNavBar, closeSpeed: closeSpeed, parentVcName: parentVcName, initialStatusBarStyle: initialStatusBarStyle)
        popAlert(id: id, immediately: immediately!, delegate: delegate, parentVcName: parentVcName, closeSpeed: closeSpeed)
    }
    
    private func hideAlert(startPositionY: Double, closeSpeed: Double, immediately: Bool) {
        let viewModel = AnyAlertAction.Dismiss.ViewModel(
            closeSpeed: closeSpeed,
            startPositionY: startPositionY,
            immediately: immediately
        )
        viewController?.hideAlert(viewModel: viewModel)
    }
    
    private func updateStatusBar(id: String, immediately: Bool, hasNavBar: Bool, closeSpeed: Double, parentVcName: String, initialStatusBarStyle: UIStatusBarStyle) {
        guard !immediately else {
            return
        }
        guard !hasNavBar else {
            return
        }
        
        let threeQuarters = Int((3.0 * closeSpeed / 4.0) * 1000)
        let delay = DispatchTime.now() + .milliseconds(threeQuarters)
        DispatchQueue.main.asyncAfter(deadline: delay) {
            if let tempArray = AnyAlertManager.shared.alerts[parentVcName] {
                let tempStatusBarStyle: UIStatusBarStyle!
                let isLast: Bool = tempArray.count == 1 && tempArray[0].dataStore?.id == id
                let isFirst: Bool = tempArray.count > 1 && tempArray[tempArray.count - 1].dataStore?.id == id
                if isLast {
                    tempStatusBarStyle = initialStatusBarStyle
                } else if isFirst {
                    tempStatusBarStyle = (tempArray[tempArray.count - 2].dataStore?.statusBarStyle)!
                } else {
                    tempStatusBarStyle = (tempArray[tempArray.count - 1].dataStore?.statusBarStyle)!
                }
                
                let viewModel = AnyAlertAction.Display.ViewModel(
                    message: "",
                    backgroundColor: .white,
                    statusBarStyle: tempStatusBarStyle,
                    messageFont: UIFont.systemFont(ofSize: 12.0),
                    messageColor: .white,
                    closeButtonFont: UIFont.systemFont(ofSize: 12.0),
                    closeButtonColor: .white,
                    openSpeed: -1.0,
                    closeSpeed: -1.0,
                    shouldHideCloseButton: false,
                    endPositionY: -1.0
                )
                self.viewController?.setStatusBarStyle(viewModel: viewModel)
            }
        }
    }
    
    private func popAlert(id: String, immediately: Bool, delegate: AnyAlertDelegate, parentVcName: String, closeSpeed: Double) {
        let delay = DispatchTime.now() + (immediately ? 0.0 : closeSpeed)
        DispatchQueue.main.asyncAfter(deadline: delay) {
            delegate.popAlert(id: id, parentVcName: parentVcName)
        }
    }
}


// MARK: - AnyAlertPresentationLogic
extension AnyAlertPresenter: AnyAlertPresentationLogic {
    
    func displayAlert(response: AnyAlertAction.Display.Response) {
        let viewModel = AnyAlertAction.Display.ViewModel(
            message: response.message,
            backgroundColor: response.backgroundColor,
            statusBarStyle: response.statusBarStyle,
            messageFont: response.messageFont,
            messageColor: response.messageColor,
            closeButtonFont: response.closeButtonFont,
            closeButtonColor: response.closeButtonColor,
            openSpeed: response.openSpeed,
            closeSpeed: -1.0,
            shouldHideCloseButton: response.doesSelfDismiss,
            endPositionY: response.endPositionY
        )
        
        viewController?.setStyle(viewModel: viewModel)
        viewController?.setMessage(viewModel: viewModel)
        viewController?.setCloseButtonVisibility(viewModel: viewModel)
        
        viewController?.showAlert(viewModel: viewModel)
        
        if !response.hasNavBar {
            let oneQuarter = Int(response.openSpeed / 4.0 * 1000.0)
            let statusBarDelay = DispatchTime.now() + .milliseconds(oneQuarter)
            DispatchQueue.main.asyncAfter(deadline: statusBarDelay) {
                self.viewController?.setStatusBarStyle(viewModel: viewModel)
            }
        }
        
        if response.doesSelfDismiss {
            let dismissDelay = DispatchTime.now() + .milliseconds(Int(response.openSpeed * 1000.0)) + .milliseconds(Int(response.showFor * 1000.0))
            DispatchQueue.main.asyncAfter(deadline: dismissDelay) {
                self.performDismissAlert(
                    delegate: response.delegate,
                    id: response.id,
                    parentVcName: response.parentVcName,
                    hasNavBar: response.hasNavBar,
                    initialStatusBarStyle: response.initialStatusBarStyle,
                    startPositionY: response.startPositionY,
                    closeSpeed: response.closeSpeed
                )
            }
        }
    }
    
    func dismissAlert(response: AnyAlertAction.Dismiss.Response) {
        performDismissAlert(
            delegate: response.delegate,
            id: response.id,
            parentVcName: response.parentVcName,
            hasNavBar: response.hasNavBar,
            initialStatusBarStyle: response.initialStatusBarStyle,
            startPositionY: response.startPositionY,
            closeSpeed: response.closeSpeed,
            immediately: response.immediately
        )
    }
}
